baseurl = "http://www.randomjy.com/"
languageCode = "en-us"
title = "random_jy"
theme = "hyde-x"
copyright = "Jon Young"

contentdir = "content"
layoutdir = "themes/hyde-x/layouts"
staticdir = "static"
publishdir = "public"

[Author]
    name = "Jon Young"

[Permalinks]
    blog = "/:year/:month/:day/:filename/"

# [Taxonomies]
#     tag = ["family", "hacker", "diy"]
#     category = ["family", "hacker", "diy"]

[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "Random thoughts on random things from JY"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    tagline = "family man, coder, diy'r"

    # integrations
    googleAnalytics = "UA-60216723-1"

    twitter = "https://twitter.com/random_jyoung"
    github = "https://github.com/thejaywhy"
    linkedin = "https://www.linkedin.com/in/jonryoung"
